use crate::P;

use super::HOST_ROUTE_COUNT;

pub(super) const ROUTES: [(P, P, P, P); HOST_ROUTE_COUNT] = [
    (
        P::Mod1Source,
        P::Mod1Target,
        P::Mod1Amount,
        P::Mod1TargetExt,
    ),
    (
        P::Mod2Source,
        P::Mod2Target,
        P::Mod2Amount,
        P::Mod2TargetExt,
    ),
    (
        P::Mod3Source,
        P::Mod3Target,
        P::Mod3Amount,
        P::Mod3TargetExt,
    ),
    (
        P::Mod4Source,
        P::Mod4Target,
        P::Mod4Amount,
        P::Mod4TargetExt,
    ),
    (
        P::Mod5Source,
        P::Mod5Target,
        P::Mod5Amount,
        P::Mod5TargetExt,
    ),
    (
        P::Mod6Source,
        P::Mod6Target,
        P::Mod6Amount,
        P::Mod6TargetExt,
    ),
    (
        P::Mod7Source,
        P::Mod7Target,
        P::Mod7Amount,
        P::Mod7TargetExt,
    ),
    (
        P::Mod8Source,
        P::Mod8Target,
        P::Mod8Amount,
        P::Mod8TargetExt,
    ),
    (
        P::Mod9Source,
        P::Mod9Target,
        P::Mod9Amount,
        P::Mod9TargetExt,
    ),
    (
        P::Mod10Source,
        P::Mod10Target,
        P::Mod10Amount,
        P::Mod10TargetExt,
    ),
    (
        P::Mod11Source,
        P::Mod11Target,
        P::Mod11Amount,
        P::Mod11TargetExt,
    ),
    (
        P::Mod12Source,
        P::Mod12Target,
        P::Mod12Amount,
        P::Mod12TargetExt,
    ),
    (
        P::Mod13Source,
        P::Mod13Target,
        P::Mod13Amount,
        P::Mod13TargetExt,
    ),
    (
        P::Mod14Source,
        P::Mod14Target,
        P::Mod14Amount,
        P::Mod14TargetExt,
    ),
    (
        P::Mod15Source,
        P::Mod15Target,
        P::Mod15Amount,
        P::Mod15TargetExt,
    ),
    (
        P::Mod16Source,
        P::Mod16Target,
        P::Mod16Amount,
        P::Mod16TargetExt,
    ),
];
