const TAPS: usize = 8;

// Eight-sample causal minimum-phase band-limited step residual, generated by
// the existing sparse minBLEP experiment. Event processing stays fixed-size,
// allocation-free, and dormant outside a gate or voice-count transition.
const RESIDUAL: [f32; TAPS] = [
    -1.0,
    -0.986_767_95,
    -0.560_396_2,
    0.141_424_9,
    -0.029_965_84,
    0.006_980_182,
    0.020_909_201,
    0.001_384_195,
];

#[derive(Clone, Copy, Default)]
pub(super) struct GainDeclicker {
    ring: [f32; TAPS],
    cursor: u8,
    remaining: u8,
    correction: f32,
}

impl GainDeclicker {
    #[inline]
    pub(super) fn insert(&mut self, jump: f32) {
        if jump.abs() <= f32::EPSILON {
            return;
        }
        let cursor = usize::from(self.cursor);
        for (tap, residual) in RESIDUAL.into_iter().enumerate() {
            let index = (cursor + tap) & (TAPS - 1);
            self.ring[index] = jump.mul_add(residual, self.ring[index]);
        }
        self.remaining = TAPS as u8;
    }

    #[inline]
    pub(super) fn advance(&mut self) {
        if self.remaining == 0 {
            self.correction = 0.0;
            return;
        }
        let cursor = usize::from(self.cursor);
        self.correction = self.ring[cursor];
        self.ring[cursor] = 0.0;
        self.cursor = ((cursor + 1) & (TAPS - 1)) as u8;
        self.remaining = self.remaining.saturating_sub(1);
    }

    pub(super) const fn correction(self) -> f32 {
        self.correction
    }

    pub(super) const fn active(self) -> bool {
        self.remaining != 0 || self.correction != 0.0
    }

    pub(super) fn reset(&mut self) {
        *self = Self::default();
    }
}

pub(super) const fn transition_samples() -> u16 {
    TAPS as u16 + 1
}

pub(super) fn transition_amount(remaining: u16) -> f32 {
    let index = TAPS + 2 - usize::from(remaining.min(transition_samples()));
    let previous = if index == 1 {
        0.0
    } else {
        1.0 + RESIDUAL[index - 2]
    };
    let current = if index > TAPS {
        1.0
    } else {
        1.0 + RESIDUAL[index - 1]
    };
    (current - previous) / (1.0 - previous)
}
